apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-tools-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-tools-read
subjects:
  - kind: ServiceAccount
    name: kubevirt-tools-sa
    namespace: kubevirt-tools
