apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-tools-app
  namespace: kubevirt-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-tools-app
  template:
    metadata:
      labels:
        app: kubevirt-tools-app
    spec:
      serviceAccountName: kubevirt-tools-sa
      containers:
        - name: kubevirt-tools
          image: hsduiii/kubevirt_tools:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: kubevirt-tools-secret
