apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-tools-secret
  namespace: kubevirt-tools
type: Opaque
stringData:
  SECRET_KEY_BASE: "REPLACE_ME"
  PHX_HOST: "localhost"
  PORT: "4000"
  PROMETHEUS_URL: "http://prometheus:9090"
