apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-tools-secret
  namespace: kubevirt-tools
type: Opaque
stringData:
  SECRET_KEY_BASE: "your_secret_key_base"
  PHX_HOST: "your_phx_host"
  PORT: 4000
  PROMETHEUS_URL: "your_prometheus_url"
